### ISSUE TITLE
Error in posting title and content

### ISSUE THREAD

**Issue by Jitendrashriram** [samarthagarwal/Scribe#3]
Hi Samarth,

I am using your code as it is but facing some issue in displaying data. also tried latest code but not working.

Trainer on Internshala 
![image](https://user-images.githubusercontent.com/72699309/97963428-245d3c00-1ddd-11eb-8cea-cf4964038aec.png)

**Comment by samarthagarwal** [comment]
Your error message mentioned the code that is not supposed to be there in `CreateComponent`'s template. Use `AngularEditor` instead.

**Comment by Jitendrashriram** [comment]
Tried @kolkov/angular-editor, now its working,

Many thanks for that
