### ISSUE TITLE
firebase auth issue

### ISSUE THREAD

**Issue by Jitendrashriram** [samarthagarwal/Scribe#4]
Hi,
 
I am facing firebase auth issue since last day, everything work well since last but when i open project firebase auth issue coming.
Property 'auth' does not exist on type 'typeof import, this error coming on all the component where i am using

![image](https://user-images.githubusercontent.com/72699309/98233330-e733ae00-1f84-11eb-944c-22be14968cc8.png)

Internshala student

**Comment by samarthagarwal** [comment]
Share the code where you import `firebase`.

**Comment by Jitendrashriram** [comment]
its solved thanks for replying.
